- name: Install docker registry on host 
  hosts: registry
  vars:
    ports_for:
      - name: registry
  tasks:
    - include_tasks: ./task-docker-install.yaml

    - name:  Ports fact
      set_fact: 
        ports: {}

    - name: Get free port
      include_tasks: ./task-get-free-port-loop.yaml
      loop: "{{ports_for}}"

    - name: Ensure the registry Docker image is pulled
      community.docker.docker_image:
        name: registry
        source: pull
        state: present
      register: image_pull_result
      become: true

    - name: Copy file to host
      copy:
        src: ./files/nginx.service
        dest: /etc/systemd/system/nginx.service
        owner: root
        group: root
        mode: '0644'
      become: true

     
    - name: Ensure a registry container is running
      community.docker.docker_container:
        name: registry 
        image: registry 
        ports:
          - "{{ports['registry']}}:5000"
        state: started
        restart_policy: always
      register: container_deploy_result
      become: true

    - name: Transfer nginx template
      ansible.builtin.template:
        src: ./files/nginx-registry.conf.j2
        dest: "/etc/nginx/sites-enabled/{{inventory_hostname}}.conf"
        backup: false
      become: true
        
    - name: Check nginx configuration
      command: nginx -t
      become: true

    - name: Restart the nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
      become: true # Requires elevated privileges to manage services

    - name: Set registry container info
      kapitan.usefull.state.set:
        key: "{{inventory_hostname}}.registry"
        value: "{{ports['registry']}}"
