- name: Gather package facts
  package_facts:
    manager: auto

- name: Install nginx if required
  when: "'nginx' not in ansible_facts.packages"
  import_tasks: role-01-nginx-install.yaml

- name: Install nginx on Debian-based Platforms
  apt:
    name: nginx
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian' and 'nginx' not in ansible_facts.packages
  become: true

- name: Install nginx on RHEL Platforms
  ansible.builtin.dnf:
    name: nginx
    state: stable
  when: ansible_facts['os_family'] == 'RedHat' and 'nginx' not in ansible_facts.packages
  become: true

- name: Start nginx module via systemd
  systemd:
    name: nginx.service
    state: started
    enabled: true
  become: true
